### ISSUE TITLE
Image to Image: AttributeError: 'AutoencoderKLOutput' object has no attribute 'sample'

### ISSUE THREAD

**Issue by jchook** [pieroit/stable-diffusion-jupyterlab-docker#3]
Getting this error on the image-to-image generator script:

```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1204/34443611.py in <module>
     11         strength = 0.8, # 0 = no noise, 1 = max noise
     12         guidance_scale = 7.5,# how much to rely on the textual prompt
---> 13         generator = generator,
     14     )
     15     display(image)

/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/project/diffusion_utils.py in __call__(self, prompt, init_image, strength, num_inference_steps, guidance_scale, eta, generator, output_type)
     72 
     73         # encode the init image into latents and scale the latents
---> 74         init_latents = self.vae.encode(init_image.to(self.device)).sample()
     75         init_latents = 0.18215 * init_latents
     76 

AttributeError: 'AutoencoderKLOutput' object has no attribute 'sample'
```

**Comment by buchbend** [comment]
I had the same issue. The solution is to change 

~~~
from diffusers import DDIMScheduler
from diffusion_utils import stable_diffusion_preprocess_image, StableDiffusionImg2ImgPipeline
~~~

to

~~~
from diffusers import DDIMScheduler, StableDiffusionImg2ImgPipeline
from diffusion_utils import stable_diffusion_preprocess_image
~~~

in the `03_image_to_image.ipynb` notebook.

The script `diffusion_utils.py` is a bit outdated `StableDiffusionImg2ImgPipeline` now part of the `diffusers` package. Information from here: https://github.com/huggingface/diffusers/issues/431

**Comment by pieroit** [comment]
@jchook and @buchbend thank you for bringing this up.
I am gonna fix it asap, if you already fixed it feel free to make a pull request ;)

P.S. don't commit your token

**Comment by buchbend** [comment]
@pieroit I'm happy to make a pull request with the fix.  But I can not push to your repository. BTW: thanks for this nice repository!

**Comment by pieroit** [comment]
@buchbend I'll give you write access to the repo

**Comment by buchbend** [comment]
@pierot Thanks! I pushed my fix and created a pull request.

**Comment by pieroit** [comment]
@buchbend anyway to do a pull request (not needed in this case, as you have write access directly on the repo), you need to:
- fork the repo
- commit and push your stuff
- push the "pull request" button on your repo

The maintainer of the main repo will be notified and can include your contributions by accepting the pull request

**Comment by pieroit** [comment]
Thank you @buchbend !
I deleted unused code from `diffusion_utils.py`

**Comment by pieroit** [comment]
@buchbend github does not show you as a contributor, it's a pity. I love that your contribution is seen on the main repo.
Try this https://stackoverflow.com/questions/40644933/not-showing-as-a-contributor-on-github

**Comment by buchbend** [comment]
> @buchbend anyway to do a pull request (not needed in this case, as you have write access directly on the repo), you need to:
> 
>     * fork the repo
> 
>     * commit and push your stuff
> 
>     * push the "pull request" button on your repo
> 
> 
> The maintainer of the main repo will be notified and can include your contributions by accepting the pull request

Thanks for the instructions. I was too quick and already pushed a branch as you've seen. Next time I know the proper way! This was first time pushing to github...
