### ISSUE TITLE
Images not sample

### ISSUE THREAD

**Issue by gavinc** [pieroit/stable-diffusion-jupyterlab-docker#9]
Running through this, found a problem with the code in:
/project/03_image_to_image.jpynb

In [5]:
image = image['sample'][0]

reports no index

changing to:
image = image['images'][0]

all good. Maybe it's my version of libs...

**Comment by pieroit** [comment]
Can you please rebuild and let me know if it is fixed?

docker-compose build --no-cache

**Comment by gavinc** [comment]
Yep, pulled again, works
